// protobuf/core/v1/callback.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: payments/core/core.proto

package pbcore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CoreCallbackService_UpdateTransactionStatus_FullMethodName = "/core.v1.CoreCallbackService/UpdateTransactionStatus"
	CoreCallbackService_ProcessExternalPayment_FullMethodName  = "/core.v1.CoreCallbackService/ProcessExternalPayment"
)

// CoreCallbackServiceClient is the client API for CoreCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreCallbackServiceClient interface {
	// Used for async updates to existing transactions (Payouts, STK Push)
	UpdateTransactionStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*CallbackResponse, error)
	// Used for unprompted externally initiated payments (Lipa na M-Pesa C2B)
	ProcessExternalPayment(ctx context.Context, in *ExternalPaymentRequest, opts ...grpc.CallOption) (*CallbackResponse, error)
}

type coreCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreCallbackServiceClient(cc grpc.ClientConnInterface) CoreCallbackServiceClient {
	return &coreCallbackServiceClient{cc}
}

func (c *coreCallbackServiceClient) UpdateTransactionStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*CallbackResponse, error) {
	out := new(CallbackResponse)
	err := c.cc.Invoke(ctx, CoreCallbackService_UpdateTransactionStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreCallbackServiceClient) ProcessExternalPayment(ctx context.Context, in *ExternalPaymentRequest, opts ...grpc.CallOption) (*CallbackResponse, error) {
	out := new(CallbackResponse)
	err := c.cc.Invoke(ctx, CoreCallbackService_ProcessExternalPayment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreCallbackServiceServer is the server API for CoreCallbackService service.
// All implementations must embed UnimplementedCoreCallbackServiceServer
// for forward compatibility
type CoreCallbackServiceServer interface {
	// Used for async updates to existing transactions (Payouts, STK Push)
	UpdateTransactionStatus(context.Context, *UpdateStatusRequest) (*CallbackResponse, error)
	// Used for unprompted externally initiated payments (Lipa na M-Pesa C2B)
	ProcessExternalPayment(context.Context, *ExternalPaymentRequest) (*CallbackResponse, error)
	mustEmbedUnimplementedCoreCallbackServiceServer()
}

// UnimplementedCoreCallbackServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCoreCallbackServiceServer struct {
}

func (UnimplementedCoreCallbackServiceServer) UpdateTransactionStatus(context.Context, *UpdateStatusRequest) (*CallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTransactionStatus not implemented")
}
func (UnimplementedCoreCallbackServiceServer) ProcessExternalPayment(context.Context, *ExternalPaymentRequest) (*CallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessExternalPayment not implemented")
}
func (UnimplementedCoreCallbackServiceServer) mustEmbedUnimplementedCoreCallbackServiceServer() {}

// UnsafeCoreCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreCallbackServiceServer will
// result in compilation errors.
type UnsafeCoreCallbackServiceServer interface {
	mustEmbedUnimplementedCoreCallbackServiceServer()
}

func RegisterCoreCallbackServiceServer(s grpc.ServiceRegistrar, srv CoreCallbackServiceServer) {
	s.RegisterService(&CoreCallbackService_ServiceDesc, srv)
}

func _CoreCallbackService_UpdateTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreCallbackServiceServer).UpdateTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreCallbackService_UpdateTransactionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreCallbackServiceServer).UpdateTransactionStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreCallbackService_ProcessExternalPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreCallbackServiceServer).ProcessExternalPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreCallbackService_ProcessExternalPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreCallbackServiceServer).ProcessExternalPayment(ctx, req.(*ExternalPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreCallbackService_ServiceDesc is the grpc.ServiceDesc for CoreCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.v1.CoreCallbackService",
	HandlerType: (*CoreCallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateTransactionStatus",
			Handler:    _CoreCallbackService_UpdateTransactionStatus_Handler,
		},
		{
			MethodName: "ProcessExternalPayment",
			Handler:    _CoreCallbackService_ProcessExternalPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payments/core/core.proto",
}
