// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: campaign/campaign.proto

package campaign

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CampaignExecutionService_EvaluatePlay_FullMethodName = "/campaign.CampaignExecutionService/EvaluatePlay"
)

// CampaignExecutionServiceClient is the client API for CampaignExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CampaignExecutionServiceClient interface {
	// EvaluatePlay checks the player's limits and the campaign's global/daily budget
	// to dictate the maximum allowable win and the active paytable.
	EvaluatePlay(ctx context.Context, in *PlayEvaluationRequest, opts ...grpc.CallOption) (*PlayEvaluationResponse, error)
}

type campaignExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCampaignExecutionServiceClient(cc grpc.ClientConnInterface) CampaignExecutionServiceClient {
	return &campaignExecutionServiceClient{cc}
}

func (c *campaignExecutionServiceClient) EvaluatePlay(ctx context.Context, in *PlayEvaluationRequest, opts ...grpc.CallOption) (*PlayEvaluationResponse, error) {
	out := new(PlayEvaluationResponse)
	err := c.cc.Invoke(ctx, CampaignExecutionService_EvaluatePlay_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignExecutionServiceServer is the server API for CampaignExecutionService service.
// All implementations must embed UnimplementedCampaignExecutionServiceServer
// for forward compatibility
type CampaignExecutionServiceServer interface {
	// EvaluatePlay checks the player's limits and the campaign's global/daily budget
	// to dictate the maximum allowable win and the active paytable.
	EvaluatePlay(context.Context, *PlayEvaluationRequest) (*PlayEvaluationResponse, error)
	mustEmbedUnimplementedCampaignExecutionServiceServer()
}

// UnimplementedCampaignExecutionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCampaignExecutionServiceServer struct {
}

func (UnimplementedCampaignExecutionServiceServer) EvaluatePlay(context.Context, *PlayEvaluationRequest) (*PlayEvaluationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluatePlay not implemented")
}
func (UnimplementedCampaignExecutionServiceServer) mustEmbedUnimplementedCampaignExecutionServiceServer() {
}

// UnsafeCampaignExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CampaignExecutionServiceServer will
// result in compilation errors.
type UnsafeCampaignExecutionServiceServer interface {
	mustEmbedUnimplementedCampaignExecutionServiceServer()
}

func RegisterCampaignExecutionServiceServer(s grpc.ServiceRegistrar, srv CampaignExecutionServiceServer) {
	s.RegisterService(&CampaignExecutionService_ServiceDesc, srv)
}

func _CampaignExecutionService_EvaluatePlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayEvaluationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignExecutionServiceServer).EvaluatePlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignExecutionService_EvaluatePlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignExecutionServiceServer).EvaluatePlay(ctx, req.(*PlayEvaluationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CampaignExecutionService_ServiceDesc is the grpc.ServiceDesc for CampaignExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CampaignExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "campaign.CampaignExecutionService",
	HandlerType: (*CampaignExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluatePlay",
			Handler:    _CampaignExecutionService_EvaluatePlay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "campaign/campaign.proto",
}
