// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: campaign/campaign.proto

package campaign

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlayEvaluationRequest contains the required context from the game engine
// to identify the player and the target promotional budget.
type PlayEvaluationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId   string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CampaignId string `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	GameId     string `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerId   string `protobuf:"bytes,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *PlayEvaluationRequest) Reset() {
	*x = PlayEvaluationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_campaign_campaign_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayEvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayEvaluationRequest) ProtoMessage() {}

func (x *PlayEvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_campaign_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayEvaluationRequest.ProtoReflect.Descriptor instead.
func (*PlayEvaluationRequest) Descriptor() ([]byte, []int) {
	return file_campaign_campaign_proto_rawDescGZIP(), []int{0}
}

func (x *PlayEvaluationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PlayEvaluationRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *PlayEvaluationRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayEvaluationRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// BudgetConstraint dictates the financial constraints for a specific reward type.
type BudgetConstraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RewardType       string  `protobuf:"bytes,1,opt,name=reward_type,json=rewardType,proto3" json:"reward_type,omitempty"` // e.g., "cash", "bonus", "points"
	ActivePaytableId string  `protobuf:"bytes,2,opt,name=active_paytable_id,json=activePaytableId,proto3" json:"active_paytable_id,omitempty"`
	MaxAllowedWin    float64 `protobuf:"fixed64,3,opt,name=max_allowed_win,json=maxAllowedWin,proto3" json:"max_allowed_win,omitempty"`
}

func (x *BudgetConstraint) Reset() {
	*x = BudgetConstraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_campaign_campaign_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BudgetConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetConstraint) ProtoMessage() {}

func (x *BudgetConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_campaign_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetConstraint.ProtoReflect.Descriptor instead.
func (*BudgetConstraint) Descriptor() ([]byte, []int) {
	return file_campaign_campaign_proto_rawDescGZIP(), []int{1}
}

func (x *BudgetConstraint) GetRewardType() string {
	if x != nil {
		return x.RewardType
	}
	return ""
}

func (x *BudgetConstraint) GetActivePaytableId() string {
	if x != nil {
		return x.ActivePaytableId
	}
	return ""
}

func (x *BudgetConstraint) GetMaxAllowedWin() float64 {
	if x != nil {
		return x.MaxAllowedWin
	}
	return 0
}

// PlayEvaluationResponse strictly dictates the financial constraints the RNG
// must adhere to for this specific spin across multiple reward types.
type PlayEvaluationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allowed            bool   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason             string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ResolvedCampaignId string `protobuf:"bytes,3,opt,name=resolved_campaign_id,json=resolvedCampaignId,proto3" json:"resolved_campaign_id,omitempty"`
	// Array of limits mapped to specific reward types
	Budgets []*BudgetConstraint `protobuf:"bytes,4,rep,name=budgets,proto3" json:"budgets,omitempty"`
}

func (x *PlayEvaluationResponse) Reset() {
	*x = PlayEvaluationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_campaign_campaign_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayEvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayEvaluationResponse) ProtoMessage() {}

func (x *PlayEvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaign_campaign_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayEvaluationResponse.ProtoReflect.Descriptor instead.
func (*PlayEvaluationResponse) Descriptor() ([]byte, []int) {
	return file_campaign_campaign_proto_rawDescGZIP(), []int{2}
}

func (x *PlayEvaluationResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *PlayEvaluationResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PlayEvaluationResponse) GetResolvedCampaignId() string {
	if x != nil {
		return x.ResolvedCampaignId
	}
	return ""
}

func (x *PlayEvaluationResponse) GetBudgets() []*BudgetConstraint {
	if x != nil {
		return x.Budgets
	}
	return nil
}

var File_campaign_campaign_proto protoreflect.FileDescriptor

var file_campaign_campaign_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x2f, 0x63, 0x61, 0x6d, 0x70, 0x61,
	0x69, 0x67, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x61, 0x6d, 0x70, 0x61,
	0x69, 0x67, 0x6e, 0x22, 0x8b, 0x01, 0x0a, 0x15, 0x50, 0x6c, 0x61, 0x79, 0x45, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61,
	0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x89, 0x01, 0x0a, 0x10, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x5f, 0x70, 0x61, 0x79, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x61, 0x79, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x5f, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x5f, 0x77, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d,
	0x6d, 0x61, 0x78, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x57, 0x69, 0x6e, 0x22, 0xb2, 0x01,
	0x0a, 0x16, 0x50, 0x6c, 0x61, 0x79, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x14, 0x72, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x5f, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x64, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x07,
	0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x2e, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x52, 0x07, 0x62, 0x75, 0x64, 0x67, 0x65,
	0x74, 0x73, 0x32, 0x6d, 0x0a, 0x18, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51,
	0x0a, 0x0c, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x12, 0x1f,
	0x2e, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x45, 0x76,
	0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x45,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x6f, 0x75, 0x63, 0x68, 0x76, 0x61, 0x73, 0x67, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x63, 0x61,
	0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_campaign_campaign_proto_rawDescOnce sync.Once
	file_campaign_campaign_proto_rawDescData = file_campaign_campaign_proto_rawDesc
)

func file_campaign_campaign_proto_rawDescGZIP() []byte {
	file_campaign_campaign_proto_rawDescOnce.Do(func() {
		file_campaign_campaign_proto_rawDescData = protoimpl.X.CompressGZIP(file_campaign_campaign_proto_rawDescData)
	})
	return file_campaign_campaign_proto_rawDescData
}

var file_campaign_campaign_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_campaign_campaign_proto_goTypes = []interface{}{
	(*PlayEvaluationRequest)(nil),  // 0: campaign.PlayEvaluationRequest
	(*BudgetConstraint)(nil),       // 1: campaign.BudgetConstraint
	(*PlayEvaluationResponse)(nil), // 2: campaign.PlayEvaluationResponse
}
var file_campaign_campaign_proto_depIdxs = []int32{
	1, // 0: campaign.PlayEvaluationResponse.budgets:type_name -> campaign.BudgetConstraint
	0, // 1: campaign.CampaignExecutionService.EvaluatePlay:input_type -> campaign.PlayEvaluationRequest
	2, // 2: campaign.CampaignExecutionService.EvaluatePlay:output_type -> campaign.PlayEvaluationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_campaign_campaign_proto_init() }
func file_campaign_campaign_proto_init() {
	if File_campaign_campaign_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_campaign_campaign_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayEvaluationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_campaign_campaign_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BudgetConstraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_campaign_campaign_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayEvaluationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_campaign_campaign_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_campaign_campaign_proto_goTypes,
		DependencyIndexes: file_campaign_campaign_proto_depIdxs,
		MessageInfos:      file_campaign_campaign_proto_msgTypes,
	}.Build()
	File_campaign_campaign_proto = out.File
	file_campaign_campaign_proto_rawDesc = nil
	file_campaign_campaign_proto_goTypes = nil
	file_campaign_campaign_proto_depIdxs = nil
}
